---
title: "Project Introduction: Soil C Modelling in Morrocan agriculture"
author: "Dr Alasdair Sykes"
date: "23/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Introduction

#### 1.1. Goal of project
The overall goal of this project is to use an internationally parameterised steady state soil carbon model to estimate the soil carbon stocks, and the potential for soil carbon stock change, in Morocco’s agricultural production systems.

#### 1.2. Skills developed
This project will combine spatial data, agricultural statistics and climate models with a steady-state soil C modelling approach. Key skill development will be:

* Understanding of steady-state soil carbon models
* Designing, scoping and executing modelling studies
* Model scenario testing and sensitivity testing
* Use of the R programming language
* Manipulation and harmonisation of spatial data
* Big data handling and analysis in the R environment

#### 1.3. Overview of task
You have been provided with an implementation of the IPCC (2019) steady-state soil C stock model for global croplands. This model is capable of estimating C stocks---and stock change over time---in soils under croplands. It has been parameterised such that it is possible to utilise this model anywhere in the world under crop production.

Your task will be to define and execute a series of cases studies using this model (in the order of 3--5, though the exact number is up to you) which examine the potential for C sequestration under Moroccan agricultural systems, and are as *representative* of Moroccan agriculture as a whole as possible.

To do this, you will need to:

1. Decide, based on available agricultural statistics and gridded data, which crops and agricultural areas should form the basis of your case studies.

2. Source, extract and format model input data for each of these case studies.

3. Run the model and analyse the results.

More detail on each of these tasks is provided below in section 4.

## 2. How does the model work?
The model is a simplified, three-pool soil carbon model. These three pools are differentiated primarily by different decay rates (i.e. rates at which soil carbon is lost, via microbial mineralisation, to the atmosphere as CO~2~). These pools are:

1. The active pool, which varies the most year on year, and has the highest rates of inputs and decay. It is fed by organic C inputs and by the slow and passive pools.

2. The slow pool, which varies less than the active pool and has lower decay rates. It is fed by the active pool and by organic C inputs.

3. The passive pool, which has the slowest rates of input and decay. It is fed by the active and slow pools only---it does not receive any direct organic C inputs.

The model simulates the flow of organic carbon into, out of and between these pools. The result can be used to estimate the net removal or addition of CO~2~ to or from the atmosphere. Environmental parameters for the model include monthly temperature, monthly precipitation, monthly potential evapotranspiration and soil sand fraction. Management related parameters include C inputs from crops, lignin and N content of organic matter, tillage practices and manure inputs. All of these things affect how quickly the pools gain and lose carbon, and how carbon flows between them.

## 3. Getting started
This tutorial will involve using R and RStudio. For those of you who are less than confident in this environment, fear not---it is entirely possible to complete the tutorial, and its learning objectives, to a high standard **without** doing any coding whatsoever. For those R enthusiasts amongst you, you will have all of the code with which this model was built and executed, and you play with it as much as you like.

Regardless of where you are on the R enthusiasm scale, you need to make sure of the following before you start:

1. You have R version 3.6.2 or higher installed on your computer. You can check the version of R you are running by typing `R.version.string` into the console, and R will return the version for you. If you are not running v3.6.2 (or you don't have R installed at all), [this page](https://uvastatlab.github.io/phdplus/installR.html) provides install links for Windows and MacOS.

2. You have RStudio version 1.2.5033 or higher installed on your computer. You can check this by opening RStudio and going to 'About RStudio' on the top menu (the exact location varies depending on Mac/Windows layouts). If you don't have this version installed, you can find the install link for Mac and Windows [here](https://rstudio.com/products/rstudio/download/#download).

3. You have the `tidyverse` and `shiny` packages installed and up to date. This is crucial---the model won't run without this step! This simplest way to check this is to type `install.packages(c("tidyverse", "shiny"))` into the console and hit return. If you don't have them installed, this will install them; if you do, it'll update them as necessary.

> Note: I realise it's annoying to go through these steps before starting. It's good practice to update your R/RStudio versions regularly---it saves annoying errors and time wasted trying to figure out why. If you really want to skip the first two steps, you can, but if anything goes wrong when running the model, please come back to this stage and update everything as a first port of call. The last step (installing your packages) is not optional, and all you will get is pain and error messages if you skip this one!

## 4. Tasks

### 3.1. Definition of study scope and selection of case studies



### 3.2. Set up and run model



### 3.3. Results analysis

